---
- name: Cleanup Nomad folder
  ansible.builtin.file:
    path: /opt/nomad
    state: absent
  ignore_errors: true
  tags: cleanup

- name: Cleanup Consul folder
  ansible.builtin.file:
    path: /opt/consul
    state: absent
  ignore_errors: true
  tags: cleanup

- name: Cleanup MAXOUT folder
  ansible.builtin.file:
    path: /opt/maxout
    state: absent
  ignore_errors: true
  tags: cleanup