---
- name: Install prerequisites (wget, Docker)
  ansible.builtin.import_tasks: install_prerequisites.yml

- name: Install Nomad
  ansible.builtin.import_tasks: install_nomad.yml

- name: Set up Maxout environment
  ansible.builtin.import_tasks: setup_maxout.yml

- name: Manage Nomad services (server and client)
  ansible.builtin.import_tasks: manage_nomad_services.yml

- name: Bootstrap ACL system
  ansible.builtin.import_tasks: bootstrap_acl.yml

- name: Update Nomad secrets
  ansible.builtin.import_tasks: update_secrets.yml