- name: Update nomad-var with the secrets
  when: 
    - ansible_host_private_ip == critical_services_ips[0]
  block:
    - name: Update secrets in nomad-var
      ansible.builtin.shell: |
        set -o pipefail
        management_token=$(grep 'Secret ID' "/opt/maxout/nomad_data/management_token.txt"  | awk '{print $NF}')
        nomad var get -namespace default -token "$management_token" nomad/jobs | \
        nomad var put -namespace default -token "$management_token" -in=json -out=table - \
            jwt_secret="{{ cluster_config.jwt_secret }}" \
            sendgrid_api_key="{{ cluster_config.sendgrid_api_key }}" \
            gemini_api_key="{{ cluster_config.gemini_api_key }}" \
            openai_api_key="{{ cluster_config.openai_api_key }}" > /dev/null
      args:
        executable: /bin/bash
      changed_when: false
      register: result

    - name: Fail if updating SQL URI failed
      ansible.builtin.fail:
        msg: "Failed to update SQL URI in Nomad on {{ ansible_host }}."
      when: result is failed
  rescue:
    - name: Fail playbook with error
      ansible.builtin.fail:
        msg: "Updating SQL URI in Nomad failed on {{ ansible_host }}."