---
- name: Initialize sql_clients variables of client nodes
  ansible.builtin.set_fact:
    sql_clients: []

- name: Set up sql_clients variable
  ansible.builtin.set_fact:
    sql_clients: "{{ sql_clients | default([]) + [item.private_ip] }}"
  when: 
    - cluster_config.self_hosted_sql_server
    - "'roles' not in item or 'sql_server' not in item.roles"
  loop: "{{ nodes }}"