---
- name: Install OpenSSL and set up directory
  ansible.builtin.import_tasks: install_and_setup_directory.yml

- name: Generate SSL certificate and configure certificates.toml
  ansible.builtin.import_tasks: generate_certificate_and_configure.yml