---
- name: Install Consul
  block:
    - name: Install Consul on Ubuntu
      ansible.builtin.shell: |
        set -o pipefail
        sudo apt-get install -y gpg coreutils gnupg
        keyring_file="/usr/share/keyrings/hashicorp-archive-keyring.gpg"
        if [ -f "$keyring_file" ]; then
          sudo rm "$keyring_file"
        fi
        wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o "$keyring_file"
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update && sudo apt install -y consul="1.19.2-1" --allow-downgrades
      args:
        executable: /bin/bash
      when: ansible_pkg_mgr == "apt"
      register: result_apt
      changed_when: false

    - name: Install Consul on Amazon Linux (dnf)
      ansible.builtin.shell: |
        set -o pipefail
        sudo dnf install -y dnf-plugins-core shadow-utils
        sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
        sudo dnf -y install consul-1.19.1
      args:
        executable: /bin/bash
      when: ansible_pkg_mgr == "dnf" or (ansible_distribution == "Amazon" and ansible_distribution_version == "2023")
      register: result_dnf
      changed_when: false

    - name: Install Consul on Amazon Linux 2 (fallback to yum)
      ansible.builtin.shell: |
        set -o pipefail
        sudo yum install -y yum-utils shadow-utils
        sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
        sudo yum -y install consul-1.19.1
      args:
        executable: /bin/bash
      when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
      register: result_yum
      changed_when: false

    - name: Fail if Consul installation failed
      ansible.builtin.fail:
        msg: "Failed to install Consul on {{ ansible_host }}. Error: {{ result }}"
      when:
        - (ansible_pkg_mgr == "apt" and result_apt is failed) or
          (ansible_pkg_mgr == "dnf" and result_dnf is failed) or
          (ansible_distribution == "Amazon" and ansible_distribution_version == "2" and result_yum is failed)

  rescue:
    - name: Rollback - Remove Consul and related packages if installation failed on Ubuntu
      ansible.builtin.shell: |
        sudo apt-get purge -y consul
        sudo rm -rf /etc/apt/sources.list.d/hashicorp.list /usr/share/keyrings/hashicorp-archive-keyring.gpg
      args:
        executable: /bin/bash
      when: ansible_pkg_mgr == "apt"
      ignore_errors: true

    - name: Rollback - Remove Consul and related packages if installation failed on Amazon Linux (dnf)
      ansible.builtin.shell: |
        sudo dnf remove -y consul dnf-plugins-core shadow-utils
        sudo rm -f /etc/yum.repos.d/hashicorp.repo
      args:
        executable: /bin/bash
      when: ansible_pkg_mgr == "dnf" or (ansible_distribution == "Amazon" and ansible_distribution_version == "2023")
      ignore_errors: true

    - name: Rollback - Remove Consul and related packages if installation failed on Amazon Linux 2 (yum)
      ansible.builtin.shell: |
        sudo yum remove -y consul yum-utils shadow-utils
        sudo rm -f /etc/yum.repos.d/hashicorp.repo
      args:
        executable: /bin/bash
      when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
      ignore_errors: true

    - name: Fail playbook with error
      ansible.builtin.fail:
        msg: "Installation of Consul failed and rollback performed on {{ ansible_host }}."