nodes:
  - name: "node3" # Replace with a unique name for the node.
    private_ip: "192.168.0.12" # Replace with the private IP address of the node.
    ssh_username: "" # Replace with the SSH username for the node (typically "ubuntu" for AWS Ubuntu, "ec2-user" for AWS Amazon Linux).

    connection_type:
      "ssh" # Defaults to "ssh", meaning Ansible will connect to this node using an SSH client.
      # You can set this to "local" if the node is the local machine where Ansible is running,
      # in which case Ansible will install all libraries directly on the local host without using SSH.

    private_key:
      "" # Path to the SSH private key for this node.
      # Leave as "" if you have direct SSH access from the host or the host is already trusted.

    ssh_common_args:
      "" # Optional: If no private key is used, specify additional SSH options here.
      # Leave this empty ("") if you use `private_key` or direct SSH access.
  
  - name: "node4" # Replace with a unique name for the node.
    private_ip: "192.168.0.13" # Replace with the private IP address of the node.
    ssh_username: "" # Replace with the SSH username for the node (typically "ubuntu" for AWS Ubuntu, "ec2-user" for AWS Amazon Linux).

    connection_type:
      "ssh" # Defaults to "ssh", meaning Ansible will connect to this node using an SSH client.
      # You can set this to "local" if the node is the local machine where Ansible is running,
      # in which case Ansible will install all libraries directly on the local host without using SSH.

    private_key:
      "" # Path to the SSH private key for this node.
      # Leave as "" if you have direct SSH access from the host or the host is already trusted.

    ssh_common_args:
      "" # Optional: If no private key is used, specify additional SSH options here.
      # Leave this empty ("") if you use `private_key` or direct SSH access.